from dotenv import load_dotenv
from langchain.prompts import ChatPromptTemplate
from langchain_openai import ChatOpenAI
from langchain.schema.output_parser import StrOutputParser
from langchain.schema.runnable import RunnableLambda

# Load environment variables
load_dotenv()

# Initialize the OpenAI model
model = ChatOpenAI(model="gpt-3.5-turbo")

# Define the prompt template
prompt_template = ChatPromptTemplate.from_messages([
    ("system", "You are a comedian who tells jokes about {topic}"),
    ("human", "Tell me {joke_count} jokes.")
])

# Define Runnable components
uppercase_output = RunnableLambda(lambda x: x.upper())
count_words = RunnableLambda(lambda x: f"Word count: {len(x.split())}\n{x}")
add_footer = RunnableLambda(lambda x: x + "\n\n-----------\nGenerated by ChatGPT")


# Define the full chain
chain = prompt_template | model | StrOutputParser() | count_words | add_footer

# Input for the chain
input_data = {
    "topic": "Doctor",
    "joke_count": 5,
    "condition": "uppercase"  # Choose "uppercase" or "reverse" for the branch
}

# Execute the chain
result = chain.invoke(input_data)

# Print the result
print(result)
